spring:
  redis:
    host: ${REDIS_HOST}
    port: 14472
    password : ${REDIS_PASS}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true

server:
  port: ${SERVER_PORT}
  servlet :
    context-path : /journal


weather :
  api :
    key : ${WEATHER_API_KEY}

#weather_api_key :