spring:
  redis:
    host: ${REDIS_HOST}
    port: 14472
    password : ${REDIS_PASS}
  data:
    mongodb:  
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}

  mvc:
    static-path-pattern: /**
  web:
    resources:
      add-mappings: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.spring.journalApp.model

server:
  port: 8081
  servlet :
    context-path : /journal


weather :
  api :
    key : ${WEATHER_API}



